### PR TITLE
Replace js use native color picker

### PR DESCRIPTION
**Pull request by MrTango**

### CODE REVIEW

**Comment by MrTango** [comment]
@mauritsvanrees you have to collective rights on PyPi to make a release then, right?

**Comment by MrTango** [comment]
could use an upgrade step to remove the existing resource bundle, as we don't need it any more or we just mention it in the README, it's not to hard to do by hand.

**Review by petschki — APPROVED** [review]
LGTM

**Comment by mauritsvanrees** [comment]
I have released 3.0.0 to PyPI.

**Pull request merged**
